# Generated by Django 3.2.7 on 2021-09-22 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0003_auto_20210921_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvehicle',
            name='cap_sz',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tvehicle',
            name='cap_wt',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('wt', models.IntegerField()),
                ('sz', models.IntegerField()),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=160)),
                ('status', models.CharField(max_length=50)),
                ('tvehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.tvehicle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
