# Generated by Django 3.2.7 on 2021-09-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20210922_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='status',
            field=models.IntegerField(),
        ),
    ]
