# Generated by Django 3.2.7 on 2021-09-22 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_consignment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvehicle',
            name='pnumber',
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnumber', models.CharField(max_length=10)),
                ('vmodel', models.CharField(max_length=100)),
                ('wcap', models.IntegerField()),
                ('byear', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.packerprofile')),
            ],
        ),
        migrations.AddField(
            model_name='tvehicle',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.vehicles'),
        ),
    ]
