# Generated by Django 3.2.7 on 2021-09-22 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20210922_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.packerprofile'),
        ),
    ]
